# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.
# 基本設置
baseURL = "https://jhihsheng.github.io/"
title = "QNO"
#languageCode = "en-us"

# 主題設置
theme="academic"

# 連結設置
[permalinks]
  posts = "/:year/:month/:title/"